### ISSUE TITLE
Closing two tabs in a row can mess up the last-accessed-tab order for Ctrl+Tab

### ISSUE THREAD

**Issue by blerner** [jingyu9575/select-after-closing-current#3] opened 2017-11-22 14:52 UTC
Because Firefox doesn't properly give you control over which tab to access next, the rightmost tab will briefly be activated even if that's not the next one in the sequence.  So suppose I have a window with five tabs:

A, B, C, D, E

and the activation order I want is E, D, B, A, C -- that is, E is currently active, and when it closes go to D, then to B, then to A, lastly to C.  When I close E, the righmost tab gets activated, and then this extension activates D: those happen to be the same thing, so it's fine.  When I then close D, the rightmost tab gets activated, and then this extension activates B.  But that means C's been activated.  When I then press Ctrl+Tab to switch to the next tab, it'll switch to C and not A.

I think this might be a bug in Firefox, and not necessarily something that Select-After-Closing-Current can fix by itself.  If it is a Firefox issue, I'll reopen this there...

**Comment by jingyu9575** [comment] 2017-11-22 21:42
This can be simplified to 4 tabs: A, B, C, D with an activation order of C, B, A, D. After closing the currently active C, B is activated. Then Ctrl+Tab goes to D instead of A, because D gets briefly activated. 

The problem is that the browser's internal activation order, used by Ctrl+Tab, is different from the preferred activation order in the extension. In the example above, when C is closed, the active tab becomes D briefly then B. The extension has code to figure out that D is not wanted and avoid promoting D in the order, so the extension's order becomes B, A, D. However, Firefox doesn't know what the user wants, and it only sees that C is closed, D is activated by default, and then B is activated by an extension. Now Firefox's order becomes B, D, A, so Ctrl+Tab goes to D.

I think the extension cannot fix the internal activation order of Firefox, unless it activates every tab in the preferred order whenever one closes, which is impractical. It may be fixed if Firefox adds new APIs to change the internal order, like `browser.tabs.update(tabId, {lastAccessed: ...})`.

**Comment by blerner** [comment] 2017-11-22 21:44
That's what I was afraid of :(  I'll file a Firefox bug report, linked to this, but I'm not optimistic they'll change the API (since they seem determined to match Chrome's behavior, rather than improve upon it).

**Comment by blerner** [comment] 2017-11-22 21:56
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1419947

**Comment by jingyu9575** [comment] 2018-11-28 12:59
A new enhancement of WebExtensions API called tab successors just landed in today's Firefox Nightly Build 20181128100125. (Thanks ryan.hendrickson!)

This extension now uses it to prevent the browser's default selection, so flashing, Ctrl+Tab order changes and tab discarding incompatibility are mitigated. The issues #3, #9, #10, #11 and #12 are fixed.

Please comment in #13 if there are issues with this feature.

**Closed by jingyu9575** 2018-11-28 12:59 UTC
Labels: browser issue
